Arrays and tensors

In [11]:
import numpy as np
import torch

data_np = np.arange(6).reshape((2,3))
data_torch = torch.from_numpy(data_np)

In [12]:
data_np

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
data_torch

tensor([[0, 1, 2],
        [3, 4, 5]])

In [14]:
tensor_to_array = data_torch.numpy()
print(tensor_to_array)

[[0 1 2]
 [3 4 5]]


Module function

In [16]:
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)

print(
    'Abs: ',
    '\n|numpy|: ', np.abs(data),
    '\n|torch|: ', torch.abs(tensor)
)

Abs:  
|numpy|:  [1 2 1 2] 
|torch|:  tensor([1., 2., 1., 2.])


Matrix multiplication

In [18]:
matrix1 = [[1,2],[3,4]]
matrix2 = torch.FloatTensor(matrix1)

print(
    'Matrix multiplication: ',
    '\nin numpy: ', np.matmul(matrix1, matrix1),
    '\nin torch: ', torch.mm(matrix2, matrix2)
)

Matrix multiplication:  
in numpy:  [[ 7 10]
 [15 22]] 
in torch:  tensor([[ 7., 10.],
        [15., 22.]])
